=== BackupTheBerlios/simple/parser/sistema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

	<xs:simpleType name="tiponombre">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]([a-zA-Z0-9]{0,19})"/>
			<xs:whiteSpace value="collapse"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipovoltaje">
		<xs:restriction base="xs:integer">
		<xs:minInclusive value="-9"/>
		<xs:maxInclusive value="9"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipovoltajepositivo">
		<xs:restriction base="xs:integer">
		<xs:minInclusive value="1"/>
		<xs:maxInclusive value="9"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipovoltajenegativo">
		<xs:restriction base="xs:integer">
		<xs:minInclusive value="-9"/>
		<xs:maxInclusive value="-1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipocolor">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9a-fA-F]{6}"/>
			<xs:whiteSpace value="collapse"/>
		</xs:restriction> 
	</xs:simpleType>
	
	
	<xs:simpleType name="tipomovimientomotor">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ccw"/>
			<xs:enumeration value="cw"/>
			<xs:enumeration value="stop"/>
			<xs:enumeration value="sh"/>
			<xs:enumeration value="sa"/>
			<xs:enumeration value="parar"/>
			<xs:whiteSpace value="collapse"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipopresion">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipomagnetismo">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoluz">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipofrecuencia">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="30000"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipotiempo">
		<xs:restriction base="xs:integer">
		</xs:restriction>
	</xs:simpleType>
	
	<!--Las posiciones en que se coloquen los elementos han de ser positivas-->
	<xs:simpleType name="tipoposicion">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<!--Aqui se describe el tipo que marca la posicion de cualquier elemento-->
	<xs:group name="grupoposicion">
		<xs:sequence>
			<xs:element name="coordenadax" type="tipoposicion"/>
			<xs:element name="coordenaday" type="tipoposicion"/>
		</xs:sequence>
	</xs:group>
	
	
	<xs:group name="gruposensorpulsador">
		<xs:sequence>
			<xs:element name="entradareposo" type="tipopresion"/>
			<xs:element name="salidareposo" type="tipovoltaje"/>
			<xs:element name="entradaactivacion" type="tipopresion"/>
			<xs:element name="salidaactivacion" type="tipovoltaje"/>
		</xs:sequence>
	</xs:group>
	
	
	<xs:complexType name="tiposensorpulsador">
		<xs:sequence>
			<xs:element name="nombreelemento"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="gruposensorpulsador"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="gruposensormagnetico">
		<xs:sequence>
			<xs:element name="entradareposo" type="tipomagnetismo"/>
			<xs:element name="salidareposo" type="tipovoltaje"/>
			<xs:element name="entradaactivacion" type="tipomagnetismo"/>
			<xs:element name="salidaactivacion" type="tipovoltaje"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tiposensormagnetico">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="gruposensormagnetico"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="grupotemporizador">
		<xs:sequence>
			<xs:element name="voltajeinicial" type="tipovoltaje"/>
			<xs:element name="voltajeactivacion" type="tipovoltaje"/>
			<xs:element name="tiempo" type="tipotiempo"/>
			<xs:element name="voltajesalidainicial" type="tipovoltaje"/>
			<xs:element name="voltajesalidaentemporizacion" type="tipovoltaje"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipotemporizador">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupotemporizador"/>
		</xs:sequence>
	</xs:complexType>
	
	<!--Un rele es un interruptor mecanico controlado por una tension.Ante un voltaje
	inicial, el interruptor puede estar activado (1) o no activado (0). Se ha usado el tipo presion
	para reutilizar y porque actua de forma similar al presionado de un pulsador-->
	<xs:group name="gruporele">
		<xs:sequence>
			<xs:element name="entradainicial" type="tipovoltaje"/>
			<xs:element name="salidainicial" type="tipopresion"/>
			<xs:element name="entradaactivacion" type="tipovoltaje"/>
			<xs:element name="salidaactivacion" type="tipopresion"/>
		</xs:sequence>
	</xs:group>

	<xs:complexType name="tiporele">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="gruporele"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="grupocontador">
		<xs:sequence>
			<xs:element name="voltajeinicial" type="tipovoltaje"/>
			<xs:element name="voltajefinal" type="tipovoltaje"/>
			<xs:element name="cuentamaxima" type="xs:positiveInteger"/>
			<xs:element name="voltajeinicialreset" type="tipovoltaje"/>
			<xs:element name="voltajefinalreset" type="tipovoltaje"/>
			<xs:element name="voltajeinicialsalida" type="tipovoltaje"/>
			<xs:element name="voltajefinalsalida" type="tipovoltaje"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipocontador">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupocontador"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="grupofotosensor">
		<xs:sequence>
			<xs:element name="entradareposo" type="tipoluz"/>
			<xs:element name="salidareposo" type="tipovoltaje"/>
			<xs:element name="entradaactivacion" type="tipoluz"/>
			<xs:element name="salidaactivacion" type="tipovoltaje"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipofotosensor">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupofotosensor"/>
		</xs:sequence>
	</xs:complexType>
	
	
	
	
	
	<xs:group name="grupolampara">
		<xs:sequence>
			<xs:element name="color" type="tipocolor"/>
			<xs:element name="entradareposo" type="tipovoltaje"/>
			<xs:element name="salidareposo" type="tipoluz"/>
			<xs:element name="entradaactivacion" type="tipovoltaje"/>
			<xs:element name="salidaactivacion" type="tipoluz"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipolampara">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupolampara"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:group name="grupoelectroiman">
		<xs:sequence>
			<xs:element name="entradareposo" type="tipovoltaje"/>
			<xs:element name="salidareposo" type="tipomagnetismo"/>
			<xs:element name="entradaactivacion" type="tipovoltaje"/>
			<xs:element name="salidaactivacion" type="tipomagnetismo"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipoelectroiman">
	<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupoelectroiman"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:group name="grupozumbador">
		<xs:sequence>
			<xs:element name="entradareposo" type="tipovoltaje"/>
			<xs:element name="salidareposo" type="tipofrecuencia"/>
			<xs:element name="entradaactivacion" type="tipovoltaje"/>
			<xs:element name="salidaactivacion" type="tipofrecuencia"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipozumbador">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupozumbador"/>
		</xs:sequence> 
	</xs:complexType>
	
	<xs:group name="grupomotor">
		<xs:sequence>
			<xs:element name="entradagiro1" type="tipovoltajepositivo"/>
			<xs:element name="salidagiro1" type="tipomovimientomotor"/>
			<xs:element name="entradagiro2" type="tipovoltajenegativo"/>
			<xs:element name="salidagiro2" type="tipomovimientomotor"/>
			<xs:element name="entradareposo" type="tipovoltaje"/>
			<xs:element name="salidareposo" type="tipomovimientomotor"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tipomotor">
		<xs:sequence>
			<xs:element name="nombreelemento" type="tiponombre"/>
			<xs:group ref="grupoposicion"/>
			<xs:group ref="grupomotor"/>
		</xs:sequence>
	</xs:complexType>
	
	
	
	<xs:complexType name="tipovector">
		<xs:sequence>
			<xs:element name="numelementos" type="xs:positiveInteger"/>
			<xs:choice>
				<xs:element name="pulsador" type="tiposensorpulsador"/>
				<xs:element name="reed" type="tiposensormagnetico"/>
				<xs:element name="fotosensor" type="tipofotosensor"/>
				<xs:element name="lampara" type="tipolampara"/>
				<xs:element name="electroiman" type="tipoelectroiman"/>
				<xs:element name="motor" type="tipomotor"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="tiporelacion">
		<xs:sequence>
			<xs:element name="primario" type="tiponombre"/>
			<xs:element name="secundario" type="tiponombre"/>
		</xs:sequence>
	</xs:complexType>
		
	
	<xs:group name="elemento">
		<xs:choice>
			<xs:element name="pulsador" type="tiposensorpulsador"/>
			<xs:element name="reed" type="tiposensormagnetico"/>
			<xs:element name="fotosensor" type="tipofotosensor"/>
			<xs:element name="lampara" type="tipolampara"/>
			<xs:element name="electroiman" type="tipoelectroiman"/>
			<xs:element name="motor" type="tipomotor"/>
			<xs:element name="relacion" type="tiporelacion"/>
			<xs:element name="vector" type="tipovector"/>
			<xs:element name="temporizador" type="tipotemporizador"/>
			<xs:element name="contador" type="tipocontador"/>
			<xs:element name="zumbador" type="tipozumbador"/>
			<xs:element name="rele" type="tiporele"/>
		</xs:choice>
	</xs:group>
	
	
	<xs:complexType name="tiposistema">		
		<xs:group ref="elemento" minOccurs="1" maxOccurs="unbounded"/>
	</xs:complexType>
	
	
	<xs:element name="sistema" type="tiposistema"/>
</xs:schema>

=== BackupTheBerlios/simple/parser/proyecto.xml
<?xml version="1.0" encoding="UTF-8"?>
<sistema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation='sistema2.xsd'>
        
	<!--Ejemplo sencillo de sensor pulsador-->
	<pulsador>
		<nombreelemento>Pulsador1</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<!--Cuando a la entrada hay una presion 0 (no pulsado)...-->
		<entradareposo>0</entradareposo>
		<!--...la salida son 0 voltios... -->
		<salidareposo>
			0
		</salidareposo>
		<!--...pero cuando la entrada es una presion 1 (pulsado)... -->
		<entradaactivacion>1</entradaactivacion>
		<!--La salida son 9 Voltios-->
		<salidaactivacion>
			9
		</salidaactivacion>
	</pulsador>
	
	
	<!--Ejemplo de sensor magnetico con logica invertida. Devuelve 4V cuando no detecta
	magnetismo y 0V cuando detecta magnetismos-->
	<reed>
		<nombreelemento>reed2</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<entradareposo>	0	</entradareposo>
		<salidareposo>	4	</salidareposo>
		<entradaactivacion>	1	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</reed>
	
	<fotosensor>
		<nombreelemento>fotosensor1</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<entradareposo>	0	</entradareposo>
		<salidareposo>	9	</salidareposo>
		<entradaactivacion>	1	</entradaactivacion>
		<salidaactivacion>	9	</salidaactivacion>
	</fotosensor>
	
	<!--Una lampara que al introducir 9V devuelve luz-->
	<lampara>
		<nombreelemento>lampara3</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<color> ffaadd </color>
		<entradareposo>	9	</entradareposo>
		<salidareposo>	1	</salidareposo>
		<entradaactivacion>	0	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</lampara>
	
	<!--Este electroiman activa (1) su magnetismo cuando a la salida se presenta
	un voltaje de 9V y desactiva (0) cuando recibe 0V-->
	<electroiman>
		<nombreelemento>electroiman2</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<entradareposo>	9	</entradareposo>
		<salidareposo>	1	</salidareposo>
		<entradaactivacion>	0	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</electroiman>
	
	<rele>
		<nombreelemento>Rele1</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<entradainicial>0</entradainicial>
		<salidainicial>0</salidainicial>
		<entradaactivacion>5</entradaactivacion>
		<salidaactivacion>1</salidaactivacion>
	</rele>
	<!--Con 9V el motor gira en sentido horario, con 9 en sentido antihorario y con
	0V se detiene-->
	<motor>
		<nombreelemento>
			motor1
		</nombreelemento>
		<coordenadax>4</coordenadax>
		<coordenaday>54</coordenaday>
		<entradagiro1>	9	</entradagiro1>
		<salidagiro1>		cw	</salidagiro1>
		<entradagiro2>	-9	</entradagiro2>
		<salidagiro2>		ccw	</salidagiro2>
		<entradareposo>	0	</entradareposo>
		<salidareposo>		stop	</salidareposo>
	</motor>
	
	<relacion>
		<primario>Pulsador1</primario>
		<secundario>lampara3</secundario>
	</relacion>
	
	<lampara>
		<nombreelemento>Lampara1</nombreelemento>
		<coordenadax>4	</coordenadax>
		<coordenaday>54</coordenaday>
		<color>add3e3</color>
		<entradareposo>0</entradareposo>
		<salidareposo>0</salidareposo>
		<entradaactivacion>9</entradaactivacion>
		<salidaactivacion>1</salidaactivacion>
	</lampara>
	
	<relacion>
			<primario>Pulsador1</primario>
			<secundario>Lampara1</secundario>
	</relacion>
	
        <zumbador>
                <nombreelemento>ZumbadorA</nombreelemento>
                <coordenadax>10</coordenadax>
                <coordenaday>20</coordenaday>
		<entradareposo>0</entradareposo>
		<salidareposo>	0</salidareposo>
		<entradaactivacion>9</entradaactivacion>
		<salidaactivacion>  4000   </salidaactivacion>
	</zumbador>
	<!--Ejemplo de un vector de motores. Tiene 10 motores que con un voltaje
	de 9V giran en sentido antihorario, con un voltaje de -9V giran en sentido
	horario y con 0V detienen su actividad-->
	<vector>
		<numelementos>10</numelementos>
		<motor>
			<nombreelemento>
				vectormotores
			</nombreelemento>
			<coordenadax>10</coordenadax>
			<coordenaday>32</coordenaday>
			<entradagiro1>	9	</entradagiro1>
			<salidagiro1>		ccw	</salidagiro1>
			<entradagiro2>	-9	</entradagiro2>
			<salidagiro2>		cw	</salidagiro2>
			<entradareposo>	0	</entradareposo>
			<salidareposo>		stop	</salidareposo>
		</motor>
	</vector>
	
	
	<temporizador>
		<nombreelemento>TemporizadorXX</nombreelemento>
		<coordenadax>10</coordenadax>
		<coordenaday>32</coordenaday>
		<voltajeinicial>0</voltajeinicial>
		<voltajeactivacion>5</voltajeactivacion>
		<tiempo>12</tiempo>
		<voltajesalidainicial>0</voltajesalidainicial>
		<voltajesalidaentemporizacion>5</voltajesalidaentemporizacion>
	</temporizador>
	
	<contador>
		<nombreelemento>ContadorX</nombreelemento>
		<coordenadax>10</coordenadax>
		<coordenaday>32</coordenaday>
		<voltajeinicial>0</voltajeinicial>
		<voltajefinal>5</voltajefinal>
		<cuentamaxima>10</cuentamaxima>
		<voltajeinicialreset>0</voltajeinicialreset>
		<voltajefinalreset>5</voltajefinalreset>
		<voltajeinicialsalida>0</voltajeinicialsalida>
		<voltajefinalsalida>5</voltajefinalsalida>
	</contador>
	
	<relacion>
		<primario>Pulsador1</primario>
		<secundario>ContadorX</secundario>
	</relacion>
	
	<relacion>
		<primario>ContadorX</primario>
		<secundario>ZumbadorA</secundario>
	</relacion>
	
</sistema>

=== BackupTheBerlios/simple/tests/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<sistema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='sistema2.xsd'>	
	   
	   <nombre> Sistema1</nombre>
	<!--Ejemplo sencillo de sensor pulsador-->
	<pulsador>
		<nombreelemento>Pulsador1</nombreelemento>
		<!--Cuando a la entrada hay una presion 0 (no pulsado)...-->
		<entradareposo>
			0
		</entradareposo>
		<!--...la salida son 0 voltios... -->
		<salidareposo>
			0
		</salidareposo>
		<!--...pero cuando la entrada es una presion 1 (pulsado)... -->
		<entradaactivacion>
			1
		</entradaactivacion>
		<!--La salida son 9 Voltios-->
		<salidaactivacion>
			9
		</salidaactivacion>
	</pulsador>
	
	
	<!--Ejemplo de sensor magnetico con logica invertida. Devuelve 4V cuando no detecta
	magnetismo y 0V cuando detecta magnetismos-->
	<reed>
		<nombreelemento>reed2</nombreelemento>
		<entradareposo>	0	</entradareposo>
		<salidareposo>	4	</salidareposo>
		<entradaactivacion>	1	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</reed>
	
	<fotosensor>
		<nombreelemento>fotosensor1</nombreelemento>
		<entradareposo>	0	</entradareposo>
		<salidareposo>	9	</salidareposo>
		<entradaactivacion>	1	</entradaactivacion>
		<salidaactivacion>	9	</salidaactivacion>
	</fotosensor>
	
	<!--Una lampara que al introducir 9V devuelve luz-->
	<lampara>
		<nombreelemento>lampara3</nombreelemento>
		<color> ffaadd </color>
		<entradareposo>	9	</entradareposo>
		<salidareposo>	1	</salidareposo>
		<entradaactivacion>	0	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</lampara>
	
	<!--Este electroiman activa (1) su magnetismo cuando a la salida se presenta
	un voltaje de 9V y desactiva (0) cuando recibe 0V-->
	<electroiman>
		<nombreelemento>electroiman2</nombreelemento>
		<entradareposo>	9	</entradareposo>
		<salidareposo>	1	</salidareposo>
		<entradaactivacion>	0	</entradaactivacion>
		<salidaactivacion>	0	</salidaactivacion>
	</electroiman>
	
	<!--Con 9V el motor gira en sentido horario, con 9 en sentido antihorario y con
	0V se detiene-->
	<motor>
		<nombreelemento>
			motor1
		</nombreelemento>
		<entradagiro1>	9	</entradagiro1>
		<salidagiro1>		cw	</salidagiro1>
		<entradagiro2>	-9	</entradagiro2>
		<salidagiro2>		ccw	</salidagiro2>
		<entradareposo>	0	</entradareposo>
		<salidareposo>		stop	</salidareposo>
	</motor>
	
	<relacion>
		<primario>Pulsador1</primario>
		<secundario>lampara3</secundario>
	</relacion>
	
	<lampara>
		<nombreelemento>Lampara1</nombreelemento>
		<color>add3e3</color>
		<entradareposo>0</entradareposo>
		<salidareposo>0</salidareposo>
		<entradaactivacion>9</entradaactivacion>
		<salidaactivacion>1</salidaactivacion>
	</lampara>
	
	<relacion>
			<primario>Pulsador1</primario>
			<secundario>Lampara1</secundario>
	</relacion>
	
	<zumbador>
		<nombreelemento>ZumbadorA</nombreelemento>
		<entradareposo>0</entradareposo>
		<salidareposo>	0</salidareposo>
		<entradaactivacion>9</entradaactivacion>
		<salidaactivacion>  4000   </salidaactivacion>
	</zumbador>
	<!--Ejemplo de un vector de motores. Tiene 10 motores que con un voltaje
	de 9V giran en sentido antihorario, con un voltaje de -9V giran en sentido
	horario y con 0V detienen su actividad-->
	<vector>
		<numelementos>10</numelementos>
		<motor>
			<nombreelemento>
				vectormotores
			</nombreelemento>
			<entradagiro1>	9	</entradagiro1>
			<salidagiro1>		ccw	</salidagiro1>
			<entradagiro2>	-9	</entradagiro2>
			<salidagiro2>		cw	</salidagiro2>
			<entradareposo>	0	</entradareposo>
			<salidareposo>		stop	</salidareposo>
		</motor>
	</vector>
	
	<rele>
		<nombreelemento>pruebaRele </nombreelemento>
		<entradainicial>0</entradainicial>
		<salidainicial>0</salidainicial>
		<entradaactivacion>6</entradaactivacion>
		<salidaactivacion>1</salidaactivacion>
	</rele>
	
	<temporizador>
		<nombreelemento>TemporizadorXX</nombreelemento>
		<voltajeentradainicial>0</voltajeentradainicial>
		<voltajesalidainicial>0</voltajesalidainicial>
		<tiempo>4000</tiempo>
		<voltajeactivacion>5</voltajeactivacion>
		<voltajesalidaentimeout>5</voltajesalidaentimeout>
	</temporizador>
	
	<contador>
		<nombreelemento>ContadorX</nombreelemento>
		<entradareposo>0</entradareposo>
		<salidareposo>0</salidareposo>
		<entradaactivacion>9</entradaactivacion>
		<salidaactivacion>9</salidaactivacion>
		<numerodepulsos>40</numerodepulsos>
	</contador>
</sistema>
